### ISSUE TITLE
Running on the latest version on bungeecord.

### ISSUE THREAD

**Issue by johncsuti** [Leeeunderscore/LeeesBungeeQueue#3]
The plugin still works it just gives this issue!

https://haste.coolcomputers.info/tavosadose.sql

**Comment by Leeewith3Es** [comment]
try using 5.0.1 it just released should work on the latest waterfall / bungeecord builds what fork of those are you using

**Comment by johncsuti** [comment]
Using on bungeecord itself no fork. Just the spigot bungeecord. Also i will try 5.0.1

**Comment by johncsuti** [comment]
No change i still have the issue.

**Comment by megatron0001** [comment]
> No change i still have the issue.

Just use waterfall then

**Comment by Leeewith3Es** [comment]
please check your config some things are missing from the config so just regenerate the config on 5.0.1 and then edit it to your specific needs and then let me know if its fixxed im running it on the latest waterfall so try using that

**Comment by johncsuti** [comment]
I should not have to use waterfall in order to use this plugin in my opinion i should be able to use bungee since it builds onto bungee.

I will check my config and have it regenerate itself.
The issue is still there with a brand new config and running on 5.0.1.

**Comment by johncsuti** [comment]
Same issue when running 5.0.1 on waterfall...

**Comment by johncsuti** [comment]
I am also getting this on waterfall but not bungee.
It also no longer sends me to my queue server it just rams through to the main server.
https://haste.coolcomputers.info/tufovivese.properties
