### ISSUE TITLE
Suggestion for leeesbungeequeue

### ISSUE THREAD

**Issue by megatron0001** [Leeeunderscore/LeeesBungeeQueue#4]
Suggestion for leeesbungeequeue if the main server is down and then it like has the kicked message enabled maybe make it for the motd like 7b7t is down, try again later for the motd or something. Also make on the bukkit version of leeesbungeequeue add an option to disable chunk loading for servers that are not using papaya.

**Comment by Leeewith3Es** [comment]
#1 the plugin already has that kick message feature in the config u just gotta set it to false #2 the motd thing is not currently possible with how i have the plugin made and tbh its kinda useless i will look into it tho #3 that is not possible to do with a plugin so you should just use papaya idk why you wouldnt just use papaya
